version = 1

test_patterns = [
    "*/*_test.go"
]

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_path = "github.com/esquarer/go-rest"

[[analyzers]]
name = "test-coverage"
enabled = true
